### ISSUE TITLE
As a schema viewer, I want to collapse and uncollapse entities so that I can read the annotations and see the attributes and data types.

### ISSUE THREAD

**Issue by jabauer** [Princeton-CDH/davilajs#13]

**Comment by rlskoeser** [comment]
Let's use an icon for show/hide so we don't have to use complicated mouse/key combinations for other interactions.

**Comment by norabenedict** [comment]
THIS IS MY FAVORITE PART! I was so excited to clearly see all of the attributes from the "info" icon.
