### ISSUE TITLE
As a schema viewer, I want to arrange entities so that I can organize the display in a way that makes sense to me.

### ISSUE THREAD

**Issue by jabauer** [Princeton-CDH/davilajs#15]
- Drag is sticky by default - if user drags an entity, it should stay put
- Need a way to release back to force-directed placement

**Comment by rlskoeser** [comment]
Release in place could be a right click.  But then what about touch?  But we don't want the interface cluttered with too many icons.

**Comment by norabenedict** [comment]
These are super fun to move around, and I love the new "stickiness" of the tables that make them stay in place better than in previous versions. FABULOUS! :insert emoji party here:
