### ISSUE TITLE
As a schema viewer I want to see which attributes are primary keys and foreign keys so I can better understand how the entities relate to each other.

### ISSUE THREAD

**Issue by jabauer** [Princeton-CDH/davilajs#19]
Requires identifying primary and foreign keys when parsing the schema and then changing changing their datatype to "foreign key" or "primary key".

See implementation in DAVILA https://github.com/jabauer/DAVILA/blob/5154f25bceebf3258720780fdcb636817a0bd340/Entity.pde#L84-L106

**Comment by norabenedict** [comment]
Easy to see and identify which are the primary keys and which are the foreign keys from the AWESOME newly added "info" button! Looks great.
